openapi: 3.0.3
info:
  title: Gradbuddy backend API
  version: 1.0.0
  description: Access Gradbuddy users, scholarships, schools and other resources via API
  contact:
    name: Sani Abubakar Adam
    url: https://github.com/thernee
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: http://localhost:3000
    description: Development server
security:
  - BearerAuth: []
paths:
  /users:
    $ref: paths/users.yaml
  /users/{user_id}:
    $ref: paths/users_{user_id}.yaml
  /users/updatePassword/{user_id}:
    $ref: paths/users_updatePassword_{user_id}.yaml
  /register:
    $ref: paths/register.yaml
  /login:
    $ref: paths/login.yaml
  /logout:
    $ref: paths/logout.yaml
  /schools:
    $ref: paths/schools.yaml
  /schools/{school_id}:
    $ref: paths/schools_{school_id}.yaml
  /criteria/{school_id}:
    $ref: paths/criteria_{school_id}.yaml
  /favorites/{user_id}:
    $ref: paths/favorites_{user_id}.yaml
  /scholarships:
    $ref: paths/scholarships.yaml
  /scholarships/{school_id}:
    $ref: paths/scholarships_{school_id}.yaml
  /scholarships/{school_id}/{scholarship_id}:
    $ref: paths/scholarships_{school_id}_{scholarship_id}.yaml
  /search:
    $ref: paths/search.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer Authentication using JWT
